name: rawah
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  firebase_core: ^3.14.0
  curved_navigation_bar: ^1.0.6
  firebase_auth: ^5.6.0
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.9
  fl_chart: ^1.0.0
  flutter_dotenv: ^5.2.1
  http: ^1.4.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  flutter_markdown: ^0.6.18
  audioplayers: ^6.5.0
  confetti: ^0.8.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.7
  video_player: ^2.10.0
  shimmer: ^3.0.0
  timezone: ^0.10.1
  firebase_app_check: ^0.3.2+7
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.13.1
  firebase_messaging: ^15.2.8
  flutter_local_notifications: ^19.3.0
  intl: ^0.18.1
  permission_handler: ^11.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/rawah.jpg
    - .env
    - assets/sounds/subgoal_complete.mp3
    - assets/sounds/goal_complete.mp3
    - assets/videos/splash.mp4

flutter_launcher_icons:
  image_path: "assets/icon/flower_white.png"
  android: true
  ios: true
  adaptive_icon_background: "#29B492"
  adaptive_icon_foreground: "assets/icon/flower_white.png"



